### ISSUE TITLE
Issue provisioning auth using `needsauth.ForCommands`

### ISSUE THREAD

**Issue by kanadgupta** [1Password/shell-plugins#107]
### What does it concern?

The plugin SDK, design, or schema

### Goal or desired behavior

_(apologies in advance if this is a silly question, I'm a bit new to Go!)_

I'm attempting to create a new plugin for [`rdme`](https://www.npmjs.com/package/rdme) (see #106 #108) and I'm trying to use the `needsauth.ForCommands` helper function: https://github.com/1Password/shell-plugins/blob/33c03dd9cd7343e1fe68884d7053e242c8309312/sdk/needsauth/helpers.go#L20

When I create [a new array of commands](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L10-L28) and [pass it into this function](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L35), I would expect that each of the following commands would have the `NeedsAuthentication` rule set to `true` and therefore get the env variables provisioned properly:

```
rdme openapi
rdme docs
rdme docs:prune
rdme guides
rdme guides:prune
rdme changelogs
rdme custompages
rdme versions
rdme versions:create
rdme versions:delete
rdme versions:update
rdme categories
rdme categories:create
```

### Current behavior

When I attempt to create [the aforementioned array](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L10-L28) and [pass it into this function](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L35), env variables aren't being provisioned for the specified commands (e.g., `rdme openapi`).

I'm not sure how to debug this further but I believe it's because the plugin configuration doesn't think that those commands need auth for some reason. But when I comment out [these lines](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L13-L27) so the `commands` array only contains a single value, the env vars are provisioned as expected 🤔

### op CLI version

2.9.1

### shell-plugins local ref

9fc032cd912952889fedad98536b3099334e109f (full branch [here](https://github.com/kanadgupta/shell-plugins/commits/main))

**Comment by florisvdg** [comment]
We're working on improving this helper particular function, as your issue also proves: the signature is not intuitive enough.

To make it work, you have to pass a `[][]string`, for example:

```go
var commands = [][]string{
	[]string{"openapi"},
	[]string{"docs"},
	[]string{"docs:prune"},
	// etc...
}
```

I'm noticing there's quite some commands [listed](https://github.com/1Password/shell-plugins/blob/9fc032cd912952889fedad98536b3099334e109f/plugins/readme/rdme.go#L10-L28) that need authentication. If most commands need authentication, you could also consider reversing the rules, to always require authentication unless certain args are present:

https://github.com/1Password/shell-plugins/blob/33c03dd9cd7343e1fe68884d7053e242c8309312/sdk/needsauth/helpers.go#L48-L50

**Comment by kanadgupta** [comment]
@florisvdg got it, thank you for the explanation!

I had considered the `NotForArgs` function but we have a few confusing flag scenarios that I wasn't sure how to handle using that approach. For example, these commands don't require auth:

```sh
rdme # returns a help screen
rdme --version # returns the CLI version
```

The tricky thing is that the `--version` flag also serves to specify a project version in ReadMe for a few commands that require authentication:

```
rdme openapi --version 2.0
```

I'll play around and see what works. Thanks!

**Comment by kanadgupta** [comment]
Hey @florisvdg, I tried refactoring the array to use that signature and it doesn't appear to like this typing. Here's the array

```go
var commands = [][]string{
	[]string{"openapi"},

	[]string{"docs"},
	[]string{"docs:prune"},
	[]string{"guides"},
	[]string{"guides:prune"},

	[]string{"changelogs"},
	[]string{"custompages"},

	[]string{"versions"},
	[]string{"versions:create"},
	[]string{"versions:delete"},
	[]string{"versions:update"},

	[]string{"categories"},
	[]string{"categories:create"},
}
```
and here's the error I'm seeing when running `make readme/validate`:

```
plugins/readme/rdme.go:35:36: cannot use commands (variable of type [][]string) as type []string in argument to needsauth.ForCommands
make: *** [readme/validate] Error 2
```

Here's the commit for reference: https://github.com/1Password/shell-plugins/pull/106/commits/7541b26535cc7182d0b95ba95cd0cf17d568355a

**Comment by SimonBarendse** [comment]
Hey @kanadgupta, `needsauth.ForCommands` is a [variadic function](https://gobyexample.com/variadic-functions). You can use the following syntax to pass each command as an arg to it:

```GolangThere's more context and example about the variadic function concept in Golang here: https://gobyexample.com/variadic-functions
needsauth.ForCommands(commands...)
```

There's more context and example about the variadic function concept in Golang here: https://gobyexample.com/variadic-functions.

As Floris mentioned there's definitely room for us to improve this function and make it more intuitive. Thank you for letting us know! :green_heart:

**Comment by kanadgupta** [comment]
That fixed it[^1], thanks @SimonBarendse! Appreciate you and @florisvdg helping me navigate these Go basics 😅

[^1]: c33bba6d5471deb3d771db7d1f8e92067bd94430 for reference

**Comment by SimonBarendse** [comment]
Awesome, glad this was helpful! :smile:
