### ISSUE TITLE
Fastly cli

### ISSUE THREAD

**Issue by shyim** [1Password/shell-plugins#133]
### Platform or tool

Fastly

### Relevant links

* https://fastly.com

### Goal or desired behavior

Personal Access Token

### Contribution

- [X] I'd be up for building the plugin myself.

**Comment by arunsathiya** [comment]
I started a PR here:

- https://github.com/1Password/shell-plugins/pull/169

Hope that's okay with you, @shyim, and I welcome any feedback you may have!
