### ISSUE TITLE
New plugin: Terraform

### ISSUE THREAD

**Issue by anthonyangel** [1Password/shell-plugins#140]
### Platform or tool

Terraform 

### Relevant links

https://developer.hashicorp.com/terraform/cli/commands/login

https://developer.hashicorp.com/terraform/cli/config/config-file#credentials-1

### Goal or desired behavior

Authenticate Terraform against a remote backend (e.g. Terraform Cloud or Scalr)

### Contribution

- [X] I'd be up for building the plugin myself.

### Additional information

Running `terraform login` generates a plaintext JSON credential file. Alternatively you can specify login credentials via env vars

**Comment by anthonyangel** [comment]
Thanks Andy, I'm struggling to get these plugins to play nicely on my Chromebook (The op CLI and Linux app install and run just fine, but it looks like ChromeOS doesn't make the fingerprint reader available to Linux) so I may well not get round to this any time soon

**Comment by kennedy** [comment]
I was browsing through the documentation for CLI configuration. Interally in terraform, there is a credential helper system. I believe we can take advantage of that, and incorporate 1pass to it.

https://developer.hashicorp.com/terraform/cli/config/config-file#credentials-helpers

There is also environment variables we can use as well, but only supported in Terraform v1.2.0 and later.

https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials.

For example, my use-case use the Terraform Cloud token: `TF_TOKEN_app_terraform_io`
