### ISSUE TITLE
Proposal to remove "-v" from NotForVersion() check

### ISSUE THREAD

**Issue by arunsathiya** [1Password/shell-plugins#173]
### op CLI version

2.12.0

### Goal or desired behavior

"-v" flag in a CLI program works as expected. In the case of [Railway CLI](https://github.com/railwayapp/cli), "-v" is for verbose output.

### Current behavior

Right now, the NotForVersion() check (used in the parent NotForHelpOrVersion() check) in Shell Plugins code causes "-v" flag in Railway CLI to fail. Since different plugins use "-v" as a shorthand for either version or verbose output, the simplest solution would be to remove "-v" from the NotForVersion() check.

**Comment by arunsathiya** [comment]
I was curious to see how many repositories/projects use "-v" as a shorthand for "--verbose" but I couldn't find an exact number because Sourcegraph ran into a search limit. There are a ton though:

https://sourcegraph.com/search?q=context:global+-v%2C+--verbose&patternType=standard&sm=1&groupBy=repo

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18581859/216917582-4335f503-6f69-4cef-9d7c-78cc548ef34b.png">

**Comment by florisvdg** [comment]
To avoid too many false positives, the `NotForVersion` helper is only disabling auth for `-v` if it's is the only arg provided:

https://github.com/1Password/shell-plugins/blob/d4822d5ebb3ddf2d633316e1a2f06852bebccaf5/sdk/needsauth/helpers.go#L124-L128

There are a few examples in the test cases:
https://github.com/1Password/shell-plugins/blob/d4822d5ebb3ddf2d633316e1a2f06852bebccaf5/sdk/needsauth/helpers_test.go#L47-L66

Does that not work well already for `railway`?

**Comment by SimonBarendse** [comment]
Great spot, @arunsathiya!

In the case of CLIs for which the standard/default functions do not fit, we can always use a custom check. For example, in the case of railway, we could use `NotForExactArgs("--version")` instead of `NotForVersion()`. Let's start with that, and if we see a pattern or recurring problems with this approach, we can consider making changes or additions to the default/standard needsauth functions.
