### ISSUE TITLE
AWS - Add support to AWS_PROFILE env and profile parameter to none-interactive output

### ISSUE THREAD

**Issue by rafalmasiarek** [1Password/shell-plugins#197]
### Platform or tool

AWS

### Desired or expected behavior

Add support to `AWS_PROFILE` env variable and `--profile` parameter which results is no needed always interactive output from a 1p plugin.

### Current behavior

currently plugin doesn't respect `AWS_PROFILE` environment variable or `--profile` parameter, therefore it always returns interactive output with profile selection

For example:
```
➜ AWS_PROFILE=my-prod-profile; aws s3 ls
? Locate your AWS Access Key:  [Use arrows to move, type to filter, ? for more help]
> AWS Access Key (*********************) (My-Vault)
  Import into 1Password...
  Search in 1Password...
```
the same story is with a `--profile` parameter:
```
➜ aws s3 ls --profile my-prod-profile
? Locate your AWS Access Key:  [Use arrows to move, type to filter, ? for more help]
> AWS Access Key (*********************) (My-Vault)
  Import into 1Password...
  Search in 1Password...
```

### op CLI version

2.15.0-beta.03

**Comment by AndyTitu** [comment]
This should work now since #180 !
