### ISSUE TITLE
Switch to env var provisioners for ngrok

### ISSUE THREAD

**Issue by AndyTitu** [1Password/shell-plugins#216]
### Platform or tool

Ngrok

### Desired or expected behavior

Authtoken and api key can be provisioned via [the newly exposed env vars](https://ngrok.com/docs/ngrok-agent/#supported-env-variables) NGROK_AUTH_TOKEN and NGROK_API_KEY.

We need to realise that NGROK_API_KEY was recently introduced so maybe not all ngrok users will benefit from this yet. We should consider defining a `versionChecker` inside our plugins that would only allow the plugin to be run if the user's ngrok version is above a certain threshold.

### Current behavior

Ngrok provisions secrets using the config file. This is not as straightforward as provisioning via env vars because it involves handling already existing non-sensitive config files. It requires logic for looking at default locations as well looking at `--config` flag. The case when multiple config flags are specified is not supported because the merging behaviour does not fit with our FIFO file provisioning.

**Comment by arunsathiya** [comment]
- Just a note that I have a patch ready for it here: https://github.com/1Password/shell-plugins/pull/222
