### ISSUE TITLE
Unknown plugin terraform

### ISSUE THREAD

**Issue by unredundant** [1Password/shell-plugins#270]
### op CLI version

2.18.0

### Goal or desired behavior

Hey, really not sure what's up here, because the docs make it seem _super_ simple, and I've looked in this repo and there is a folder for a terraform plugin, but when I run `op plugin init terraform` I get an error saying `Unknown plugin: terraform`.

Running `op plugin list | grep terraform` shows no results, so... maybe this plugin is not included by default and needs to be installed somehow? But unless I'm missing something really obvious, the docs do not seem to indicate this is necessary

### Current behavior

Attempting to install terraform plugin results in error message above :(

**Comment by j178** [comment]
terraform is currently available in 2.19.0-beta.01 only. 
https://app-updates.agilebits.com/product_history/CLI2#v2190001
