### ISSUE TITLE
Executable file name generated by make should be in snake case instead of kebab case

### ISSUE THREAD

**Issue by arunsathiya** [1Password/shell-plugins#287]
### What does it concern?

The Makefile commands and tooling

### Goal or desired behavior

Executable file name generated by `make` should follow snake case instead of kebab case. In the case of `redis-cli`, `make` should generate `redis_cli.go`

### Current behavior

When the executable contains hyphen, the file generated is in kebab case. In the case of `redis-cli`, `make` generates `redis-cli.go`

<img width="417" alt="image" src="https://github.com/1Password/shell-plugins/assets/18581859/f01afca6-2839-44fc-98b9-1e70d54c493d">

### op CLI version

2.19.0-beta.01

**Comment by arunsathiya** [comment]
@sharunkumar Could you comment once? I'll assign this issue to you. Weird (but I agree that it's a good design to prevent spam assignments!) GitHub quirk that doesn't allow me to assign this to you.

**Comment by sharunkumar** [comment]
@arunsathiya howdy
