### ISSUE TITLE
No completions on CLI tools when using shell-plugins 

### ISSUE THREAD

**Issue by vdovhanych** [1Password/shell-plugins#344]
### op CLI version

2.18.0

### Goal or desired behavior

When using `op plugin` and having CLI tools being aliased to f.e. `alias doctl="op plugin run -- doctl"`, the completions for the CLI tool is lost. I would like the completions to be available on those CLI tools.

### Current behavior

When the CLI tool is aliased in this way from `op plugin run -- doctl` the completions that was available from the tool is lost. 

When using op authentication and the CLI is aliased, there is nothing on pressing the TAB
![Screenshot 2023-07-02 at 13 13 40](https://github.com/1Password/shell-plugins/assets/45185420/d3ee3944-b824-49f8-8082-6bdbb2311823)

When I remove the alias for the op plugin and press TAB now shows all available options
![Screenshot 2023-07-02 at 13 14 29](https://github.com/1Password/shell-plugins/assets/45185420/1c0ee229-1606-4197-a6f9-f6aa40507fc5)

**Comment by TiagoJMartins** [comment]
Take a look at #122, which discusses the same problem.

**Comment by vdovhanych** [comment]
Closing in favor of #122
