### ISSUE TITLE
Developer Slack workspace

### ISSUE THREAD

**Issue by maxbeatty** [1Password/shell-plugins#349]
The [Developer Slack workspace](https://join.slack.com/t/1password-devs/shared_invite/zt-1halo11ps-6o9pEv96xZ3LtX_VE0fJQA) linked to in the README and Issue template appears to require a @gitlab.com email address. I have a GitLab account but can't use their supplied noreply email. What am I missing?

**Comment by techcraver** [comment]
> 

Yes this is not expected behavior! I've submitted a ticket internally to our team. I'll follow-up here.

**Comment by techcraver** [comment]
@maxbeatty here's a proper link you can use to hop on our Slack: https://join.slack.com/t/1password-devs/shared_invite/zt-1z0rd7lro-fx4LPkQwUF89~PzpDGPe1A

**Comment by maxbeatty** [comment]
Thank you! New link works great

**Comment by techcraver** [comment]
awesome!

**Comment by sdahlbac** [comment]
This seems busted again, even the fixed link now says @gitlab.com

The old is also found here: https://github.com/1Password/terraform-provider-onepassword

**Comment by sdahlbac** [comment]
@arunsathiya that worked, thanks

**Comment by senadir** [comment]
Link here seems to be inactive https://developer.1password.com/joinslack?

**Comment by thisguymartin** [comment]
@sdahlbac   were you able to join the 1password slack group?
