### ISSUE TITLE
Skip auth for Sentry when --auth-token and --api-key are specified

### ISSUE THREAD

**Issue by arunsathiya** [1Password/shell-plugins#366]
I noticed that we don't skip auth when --auth-token and --api-key are specified. We should be doing that because custom arguments/flags input by users take precedence over 1Password-stored secrets.

https://github.com/1Password/shell-plugins/blob/0b46a42d5295cf0fa1bedbf6b6356f7f7568778e/plugins/sentry/sentry_cli.go#L10-L22

**Comment by roy9495** [comment]
Can I work on this issue?

**Comment by arunsathiya** [comment]
Yes, go for it @roy9495!
