### ISSUE TITLE
AWS Plugin Seems to be Broken

### ISSUE THREAD

**Issue by alexclst** [1Password/shell-plugins#415]
### Platform or tool

AWS

### Desired or expected behavior

The AWS CLI to work through its op shell plugin. This was the case the last time I used it, admittedly that was at least a month or so ago.

### Current behavior

When running a command such as `aws s3 list` I get the output I pasted into the next question, that seems to say the issue is that there is no relevant **default** profile in my *config* file. The thing is, yes I do not have anything in my *config* file, because `op` has worked flawlessly before for this CLI command. I should not need anything in this file, and don't want anything there as 1Password is much more secure and, frankly, portable across devices.

### Relevant log output

```shell
[ERROR] 2023/12/23 21:10:32 could not run plugin AWS CLI: failed to provision credentials, encountered error(s):
source profile "default" does not exist in your AWS config file
```

### op CLI version

2.24.0

**Comment by allymparker** [comment]
Has anyone managed to work around this?

**Comment by binamkayastha** [comment]
You just need a default profile in your `~/.aws/config` file (and still have the `~/.aws/credentials` file deleted)

```
[default]
region = us-east-1
```

You could omit the region line as well.

**Comment by alexclst** [comment]
@binamkayastha that worked for me.

**Comment by mikeyjoel** [comment]
Thanks! Decided to start using op cli and ran into this issue.
