### ISSUE TITLE
Plugins fail with `corrupt response from desktop app`

### ISSUE THREAD

**Issue by rkervella** [1Password/shell-plugins#425]
### op CLI version

2.24.0

### Goal or desired behavior

Plugins initialization and usage should work.

### Current behavior

The `op plugin init` command fails with the following error:

```
[ERROR] 2024/02/08 16:34:13 corrupt response from dektop app: SRP-x can only be set in combination with secret key
```

This seems to only occur with my professional 1password account (for which authentication is done via SSO, not sure if that matters).
I can't use installed plugins anymore either, the same error is returned from the `op` command.
This happened today after I updated the desktop application to `1Password for Mac 8.10.26 (81026021)`.
### Relevant log output

```shell
$ op plugin init aws

AWS CLI
Authenticate with AWS Access Key.

[ERROR] 2024/02/08 16:36:58 corrupt response from dektop app: SRP-x can only be set in combination with secret key

$ op plugin init gh

GitHub CLI
Authenticate with GitHub Personal Access Token.

[ERROR] 2024/02/08 16:34:13 corrupt response from dektop app: SRP-x can only be set in combination with secret key
```

**Comment by SimonBarendse** [comment]
Hi @rkervella,

we've identified the problem and are working on a mitigation and solution. In the meantime, if this is blocking you, you can [switch the desktop app to the stable channel](https://support.1password.com/betas/).

This impacts:
- Accounts authenticated with SSO or passkey
- Using the **beta** channel of desktop app (81026021)
- All functionality in CLI (not limited to Shell Plugins).

**Comment by rkervella** [comment]
Thanks @SimonBarendse I'll switch back to the release channel.

**Comment by andrew-blake** [comment]
I had this problem with Okta SSO and the Beta. Upgrading to the nightly release fixed it.

**Comment by hculea** [comment]
Hi both, 

Following up on this - indeed, switching back to either latest nightly (>81026036) or beta (>81026038) desktop apps should no longer produce an error, when using CLI or Shell Plugins with SSO accounts. 

Thank you again for reporting, and do let us know if you encounter any other issues!

Best,
Horia - Developer @ 1Password

**Comment by SimonBarendse** [comment]
Closing this issue since this is now fixed on all release channels.
