### ISSUE TITLE
New plugin: Linode

### ISSUE THREAD

**Issue by alexclst** [1Password/shell-plugins#80]
### Platform or tool

Linode

### Relevant links

* https://www.linode.com/
* https://www.linode.com/docs/products/tools/cli/get-started/
* https://www.linode.com/docs/products/tools/cli/guides/install/
* https://www.linode.com/docs/products/tools/cloud-manager/guides/cloud-api-keys/

### Goal or desired behavior

Authenticate the CLI using an API Token.

### Additional information

It would be nice if you could also optionally let us use just `linode` as the command to run.

**Comment by hculea** [comment]
Hey @alexclst, thank you for your request!

We think a Linode plugin would be awesome!

1Password Shell Plugin is open to contributions, so if you or anyone else are interested in building this plugin, please do check out our [contribution guidelines](https://github.com/1Password/shell-plugins/blob/main/CONTRIBUTING.md), and don't hesitate to reach out to us here or [on Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-1halo11ps-6o9pEv96xZ3LtX_VE0fJQA) for any help or inquiries.

Best,
Horia, Developer@1Password

**Comment by alexclst** [comment]
I haven't ever written anything in Go nor done any pull requests on public projects on Github before, but I did just [create a pull request for a linode-cli plugin](https://github.com/1Password/shell-plugins/pull/86).

**Comment by SimonBarendse** [comment]
Congrats on your first Go code and open-source pull request Alex! :tada:
