### ISSUE TITLE
Wrangler - Cloudflare Workers

### ISSUE THREAD

**Issue by shyim** [1Password/shell-plugins#89]
### Platform or tool

wrangler

### Desired or expected behavior

Wrangler is the CLI to deploy Cloudflare Workers

It's looks like really easy to support that.

https://developers.cloudflare.com/workers/wrangler/system-environment-variables/

I will look tomorrow into it

### Current behavior

Nope

**Comment by SimonBarendse** [comment]
Closed via https://github.com/1Password/shell-plugins/pull/94
