### ISSUE TITLE
Linode importer

### ISSUE THREAD

**Issue by florisvdg** [1Password/shell-plugins#91]
### Platform or tool

Linode

### Desired or expected behavior

Would be nice for the Linode plugin to support importing the token from the [`~/.config/linode-cli`](https://www.linode.com/docs/products/tools/cli/guides/install/#interactive-configuration).

### Current behavior

We're only looking at environment variables now.

**Comment by SimonBarendse** [comment]
@alexclst do you want to give the importer for Linode a shot as well? I know this is your first experience with Golang, so come join us in the [Developer Slack workspace](https://join.slack.com/t/1password-devs/shared_invite/zt-1halo11ps-6o9pEv96xZ3LtX_VE0fJQA)! It's an amazing bunch of 1Password enthusiasts and we can help in case you have any questions.

**Comment by alexclst** [comment]
@SimonBarendse I would say that I could give it a shot, except that now that I have the plugin configured I'd already deleted (actually long ago, as I'd been using secret references in `op` for a while for Linode) the config file, and it appears that the `linode-cli` will not let me remake it, at least when run through the 1Password shell plugin as it now is being done.

**Comment by SimonBarendse** [comment]
To keep 1Password Shell Plugins installed on your machine, while also running Linode one more time without 1Password Shell Plugins, you could run it [through Docker](https://hub.docker.com/r/linode/cli).

You can use the steps for using an existing config file (`-v $HOME/.config/linode-cli:/home/cli/.config/linode-cli`) so that the configuration file you create in the docker container also ends up in your home dir.

**Comment by alexclst** [comment]
@SimonBarendse I realized a simpler alternative was to just call `linode-cli` with its full path, to bypass the shell plugin. So now I have a config file, and can sometime look into the config file importer.

**Comment by SimonBarendse** [comment]
If you run into any further issues, don't hesitate to reach out! We're here to help!

**Comment by volodymyrZotov** [comment]
@alexclst Hey. I look at the file importer you added.
I'd suggest adding a test case that covers importing from a file.
Here is an example from sentry plugin. (make sure you created a folder `plugins/linode/test-fixtures` and put there the config file)
```
"config file": {
			Files: map[string]string{
				"~/.sentryclirc": plugintest.LoadFixture(t, ".sentryclirc"),
			},
			ExpectedCandidates: []sdk.ImportCandidate{
				{
					Fields: map[sdk.FieldName]string{
						fieldname.Token:        "mw4ms9tx4dci52bfr19sbj40lb0pu9w4camnf8w3hfzl8hckvkdocd28nexample",
						fieldname.Organization: "acme",
					},
				},
			},
		},
```

To generate a mock value for the token you can use `make linode/example-secrets` and use it in you test.

And I left a comment in your forked repo. It might help you to fix the issue.

**Comment by alexclst** [comment]
@volodymyrZotov Maybe I'm not looking in the right place, but I cannot find any comment on my fork anywhere.

I believe that I have added an appropriate test file and fixture based on your example, which appear to be passing `make test linode`.

I also seem to have the file import working. So if you and @SimonBarendse think this is all is needed for this importer I can create a pull request.

**Comment by volodymyrZotov** [comment]
@alexclst should be[ here ](https://github.com/1Password/shell-plugins/commit/54925307fce0ad98997f266257383d561ef80cd4#comments)

**Comment by volodymyrZotov** [comment]
@alexclst I've looked at your latest commits. That's exactly what I mentioned in the comment.
Awesome that everything works now. Sure, go ahead and create a PR👍

**Comment by arunsathiya** [comment]
- This issue can be closed as the PR has landed: https://github.com/1Password/shell-plugins/pull/113
